### ISSUE TITLE
How can we extend this to use MongoDB instead for federation?

### ISSUE THREAD

**Issue by noel123007** [bitrecycling/keycloak-user-storage-federation-spi#1]
I have a MongoDb as my legacy database and I want keycloak to use this DB for authentication etc. I have written a SPI similar to this, but without use of mongo JDBC. I have a maven project where all the dependencies are listed. But after deploying in wildfly, I get class not found exception. Its  because when a JAR is made out of the SPI I have built, the external dependencies are not included in that JAR. 

Here in this repo, you have mentioned a procedure to setup JDBC driver in keycloak. Is this step required if we use MongoDb as our DB? @bitrecycling

**Comment by bitrecycling** [comment]
Hi @noel123007 if I understand correctly:
1) usually (and I think exclusively), if using jee-containers (wildfly!), then datasources are fully managed by the container: driver and connection pool. That means even if you have some drivers in the jar / war, the mongodb has to be configured in wildfly. This is analogous to my readme: Step-By-Step points "download JDBC-Driver" through "verify successful installation"
2) this is not an issue regarding my repo, but I understand I am hard to reach otherwise :)

**Comment by noel123007** [comment]
Thank you very much.
